#!/bin/bash

Cost=0

MAKE=$(whiptail --title "Where every car is a steal" --menu "Choose a car:" 25 78 8 \
        "Altima" "15000" \
        "Supra" "45000" 3>&1 1>&2 2>&3)
if [ $MAKE == "Altima" ]; then
	Cost=$(($Cost +15000))
	else
        	if [ $MAKE == "Supra" ]; then
                	Cost=$(($Cost +45000))
		fi
fi

COLOR=$(whiptail --title "Where every car is a steal" --radiolist \
	"Choose a color:" 25 78 8 \
        "Black" "Free with cost of car" OFF \
        "Red" "Free with cost of car" OFF 3>&1 1>&2 2>&3)
if [[ $MAKE == "Altima" && $COLOR == "Black" ]]; then
	display -resize 1280x720 /home/hunter/gittest/blacknissan.jpg
fi
	if [[ $MAKE == "Altima" && $COLOR == "Red" ]]; then
		display -resize 1280x720 /home/hunter/gittest/rednissan.jpg
	fi
		if [[ $MAKE == "Supra" && $COLOR == "Black" ]]; then
			display -resize 1280x720 /home/hunter/gittest/blacksupra.jpg
		fi
			if [[ $MAKE == "Supra" && $COLOR == "Red" ]]; then
				display -resize 1280x720 /home/hunter/gittest/redsupra.jpg
			fi

UPGRADES=$(whiptail --title "Where every car is a steal" --checklist \
	"Choose additional upgrades:" 25 78 8 \
        "SunRoof" "1000" OFF \
        "Spoiler" "1000" OFF \
        "Pinstripe" "2000" OFF \
        "Grill" "1500" OFF 3>&1 1>&2 2>&3)

if [[ $UPGRADES =~ "SunRoof" ]]; then
	Cost=$(($Cost +1000))
fi
	if [[ $UPGRADES =~ "Spoiler" ]]; then
			Cost=$(($Cost +1000))
	fi
		if [[ $UPGRADES =~ "Pinstripe" ]]; then
			Cost=$(($Cost +2000))
		fi
			if [[ $UPGRADES =~ "Grill" ]]; then
				Cost=$(($Cost +1500))
			fi

FREE=$(whiptail --title "Where every car is a steal" --checklist \
	"Upgrades we are providing for free:" 25 78 8 \
        "Airbags" "FREE" ON \
        "XM" "FREE" ON \
        "Bluetooth" "FREE" ON \
        "Floormats" "FREE" ON \
	"Moonroof" "Not Included" OFF 3>&1 1>&2 2>&3)
echo "You chose a ${COLOR[@]} ${MAKE[@]} with the following upgrades: ${UPGRADES[@]}, including these free upgrades: ${FREE[@]}"
echo "The total price is $Cost"
